[workspace]
resolver = "2"

members = [
	"primitives/io",
]

[workspace.dependencies]
ripemd = { version = "0.1.3", default-features = false }

sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.39", default-features = false }

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"

lto = "fat"
codegen-units = 1
