[package]
name = "pallet-cosmos-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noirhq/horizon/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bech32 = { workspace = true }
parity-scale-codec = { workspace = true, features = [
	"derive",
], optional = true }
scale-info = { workspace = true, features = ["derive"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
cosmos-sdk-proto = { workspace = true }

# Substrate
frame-support = { workspace = true }
impl-trait-for-tuples = { workspace = true }
sp-core = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
array-bytes = { workspace = true }
base64ct = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
	"bech32/std",
	"cosmos-sdk-proto/std",
	"frame-support/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde",
	"serde_json",
	"sp-core/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-std/std",
]
with-codec = [
	"parity-scale-codec", 
	"scale-info"
]
with-serde = [
	"serde"
]
