[package]
name = "hp-crypto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noir-protocol/horizon/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
k256 = { workspace = true, features = ["ecdsa"] }
ripemd = { workspace = true }
signature = { workspace = true }

[features]
default = ["std"]
std = [
    "k256/std",
    "ripemd/std",
    "signature/std",
]
