[package]
name = "hp-rpc"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/noir-protocol/horizon/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hp-cosmos = { workspace = true, features = ["with-codec"] }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
std = [
	"hp-cosmos/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
]
